name: Build Docker Image

on:
  push:
    branches:
      - master  # Bu dalda değişiklik olduğunda tetiklenecek

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .                       # Repo kök dizini
          file: Dockerfile                 # Dockerfile'ın yolu
          push: false                      # İmajı gönderme, false yaparak

